[package]
name = "templar"
version = "0.1.0"
authors = ["Ishank Sharma <ishank.sharma@publicissapient.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
